version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - sam build -t devops/infra/template_resource.yaml --region ${REGION}
      - |
        sam package \
          --s3-bucket ${ARTIFACT_BUCKET} \
          --region ${REGION} \
          --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
    - '**/*'